Repository FreeProving/haskell-src-transformations, pull requests merged in 2020-09, with the labels that each got.

#55 Add tests for `Fresh` effect
  .hlint.yaml
  haskell-src-transformations.cabal
  src/lib/HST/CoreAlgorithm.hs
  src/lib/HST/Environment/Renaming.hs
  src/lib/HST/Feature/Optimization.hs
  src/lib/HST/Frontend/Syntax.hs
  src/lib/HST/Util/FreeVars.hs
  src/lib/HST/Util/Selectors.hs
  src/lib/HST/Util/Subst.hs
  src/test/HST/ApplicationTests.hs
  src/test/HST/Effect/FreshTests.hs
  src/test/HST/Test/Expectation.hs
  src/test/HST/Test/Parser.hs
  src/test/HST/Test/Runner.hs
  src/test/HST/Util/FreeVarsTests.hs
  src/test/HST/Util/SelectorsTests.hs
  src/test/HST/Util/SubstTests.hs
  src/test/Spec.hs
Labels: tests

#47 Add new implementation for substitutions
  .hlint.yaml
  haskell-src-transformations.cabal
  src/lib/HST/CoreAlgorithm.hs
  src/lib/HST/Environment/Renaming.hs
  src/lib/HST/Feature/Optimization.hs
  src/lib/HST/Frontend/Syntax.hs
  src/lib/HST/Util/FreeVars.hs
  src/lib/HST/Util/Selectors.hs
  src/lib/HST/Util/Subst.hs
  src/test/HST/ApplicationTests.hs
  src/test/HST/Test/Expectation.hs
  src/test/HST/Test/Parser.hs
  src/test/HST/Test/Runner.hs
  src/test/HST/Util/FreeVarsTests.hs
  src/test/HST/Util/SubstTests.hs
  src/test/Spec.hs
Labels: bug

#53 Prevent infinite loop in core algorithm
  src/lib/HST/CoreAlgorithm.hs
Labels: bug

#52 Add linter rules to restrict usage of `NoSrcSpan`
  .hlint.yaml
  haskell-src-transformations.cabal
  src/lib/HST/Application.hs
  src/lib/HST/Feature/CaseCompletion.hs
  src/lib/HST/Feature/GuardElimination.hs
  src/lib/HST/Frontend/GHC/From.hs
  src/lib/HST/Frontend/GHC/To.hs
  src/lib/HST/Frontend/GHC/Util/AnyMatch.hs
  src/lib/HST/Frontend/HSE/From.hs
  src/lib/HST/Frontend/HSE/To.hs
  src/lib/HST/Frontend/Syntax.hs
Labels: tests

#49 Add Expression Parser and Further Tests for Substitutions
  src/lib/HST/Effect/WithFrontend.hs
  src/lib/HST/Frontend/Parser.hs
  src/lib/HST/Frontend/PrettyPrinter.hs
  src/lib/HST/Frontend/Transformer.hs
  src/test/HST/ApplicationTests.hs
  src/test/HST/Test/Expectation.hs
  src/test/HST/Test/Parser.hs
  src/test/HST/Util/FreeVarsTests.hs
  src/test/HST/Util/SubstTests.hs
Labels: tests

#51 Add tests for code excerpt displaying
  haskell-src-transformations.cabal
  src/lib/HST/Effect/InputFile.hs
  src/lib/HST/Util/Messages.hs
  src/test/HST/Util/MessagesTests.hs
  src/test/Spec.hs
Labels: tests

#60 Add Tests for the Environment Lookup Functions
  .hlint.yaml
  haskell-src-transformations.cabal
  src/test/HST/Effect/SetExpectation.hs
  src/test/HST/EnvironmentTests.hs
  src/test/Spec.hs
Labels: tests

#58 Add Support for Qualified Identifiers
  .hlint.yaml
  haskell-src-transformations.cabal
  src/lib/HST/Application.hs
  src/lib/HST/CoreAlgorithm.hs
  src/lib/HST/Environment.hs
  src/lib/HST/Environment/LookupOrReport.hs
  src/lib/HST/Feature/Optimization.hs
  src/lib/HST/Frontend/Syntax.hs
  src/test/HST/Effect/SetExpectation.hs
  src/test/HST/EnvironmentTests.hs
  src/test/Spec.hs
Labels: enhancement

#56 Add support for module imports
  .hlint.yaml
  README.md
  haskell-src-transformations.cabal
  src/exe/Main.hs
  src/lib/HST/Application.hs
  src/lib/HST/CoreAlgorithm.hs
  src/lib/HST/Effect/Env.hs
  src/lib/HST/Effect/InputModule.hs
  src/lib/HST/Environment.hs
  src/lib/HST/Environment/LookupOrReport.hs
  src/lib/HST/Environment/Prelude.hs
  src/lib/HST/Feature/CaseCompletion.hs
  src/lib/HST/Feature/GuardElimination.hs
  src/lib/HST/Feature/Optimization.hs
  src/lib/HST/Frontend/GHC/From.hs
  src/lib/HST/Frontend/GHC/To.hs
  src/lib/HST/Frontend/HSE/From.hs
  src/lib/HST/Frontend/HSE/To.hs
  src/lib/HST/Frontend/Syntax.hs
  src/lib/HST/Util/FreeVars.hs
  src/lib/HST/Util/Selectors.hs
  src/test/HST/ApplicationTests.hs
  src/test/HST/Effect/SetExpectation.hs
  src/test/HST/EnvironmentTests.hs
  src/test/Spec.hs
Labels: enhancement
